name: NIRAC CI/CD

on:
  push:
    branches:
      - master

env:
  SOLUTION_NAME: NIRAC-APP.csproj
  SOLUTION_NAME_API: NIRAC-API/NIRAC-API.csproj
  SOLUTION_NAME_BUSINESS: NIRAC-BUSINESS/NIRAC-BUSINESS.csproj
  SOLUTION_NAME_TESTE: NIRAC-TESTE/NIRAC-TESTE.csproj
  DLL_TESTE: NIRAC-TESTE/bin/Release/NIRAC-TESTE.dll


jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '5.0.x'

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore Dependencies BUSINESS PROJECT
      run: nuget restore ${{ env.SOLUTION_NAME_BUSINESS }} -o packages

    - name: Restore Dependencies WebApp
      run: nuget restore ${{ env.SOLUTION_NAME }} -o packages

    - name: Restore Dependencies API
      run: nuget restore ${{ env.SOLUTION_NAME_API }} -o packages

    - name: Restore Dependencies TESTE
      run: nuget restore ${{ env.SOLUTION_NAME_TESTE }} -o packages

    - name: Build BUSINESS
      run: msbuild ${{ env.SOLUTION_NAME_BUSINESS }} /p:Configuration=Release

    - name: Build WebApp
      run: msbuild ${{ env.SOLUTION_NAME }} /p:Configuration=Release 
    
    - name: Build API
      run: msbuild ${{ env.SOLUTION_NAME_API }} /p:Configuration=Release 
    
    - name: Build TESTE
      run: msbuild ${{ env.SOLUTION_NAME_TESTE }} /p:Configuration=Release
      
    - name: restore testes
      run: dotnet restore ${{ env.SOLUTION_NAME_TESTE }}
      
    - name: Executando os testes
      run: dotnet vstest ${{ env.DLL_TESTE }}

    - name: Publicando o NIRAC-APP
      uses: dotnet publish -p:PublishProfile=FTPNIRAC.pubxml