name: NIRAC CI/CD

on:
  push:
    branches:
      - master

env:
  SOLUTION_NAME: NIRAC-APP.csproj
  SOLUTION_NAME_API: NIRAC-API/NIRAC-API.csproj
  SOLUTION_NAME_BUSINESS: NIRAC-BUSINESS/NIRAC-BUSINESS.csproj
  TEST_API: NIRAC-TESTE/bin/Debug/VsTest.Console.exe NIRAC-TESTE.dll

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '5.0.x'

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore Dependencies BUSINESS PROJECT
      run: nuget restore ${{ env.SOLUTION_NAME_BUSINESS }} -o packages

    - name: Restore Dependencies WebApp
      run: nuget restore ${{ env.SOLUTION_NAME }} -o packages

    - name: Restore Dependencies API
      run: nuget restore ${{ env.SOLUTION_NAME_API }} -o packages

    - name: Build WebApp
      run: msbuild ${{ env.SOLUTION_NAME }} /p:Configuration=Release 
    
    - name: Build API
      run: msbuild ${{ env.SOLUTION_NAME_API }} /p:Configuration=Release 
      
    - name: Executando os testes
      run: ${{ env.TEST_API }}