name: NIRAC CI/CD

on:
  push:
    branches:
      - master

env:
  SOLUTION_NAME: NIRAC-APP.csproj

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '5.0.x'

    - name: Setup MSBuild Path
      uses: Disneyjr/NIRAC-WEB@v1
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore Dependencies
      run: nuget restore ${{ env.SOLUTION_NAME }}

    - name: Build App
      run: msbuild ${{ env.SOLUTION_NAME }} /p:Configuration=Release 
    #- name: Setup NuGet
    #  uses: NuGet/setup-nuget@v1.0.2
    
    #- name: Restore NuGet packages
    #  run: nuget restore ${{ env.WEBAPP_NAME }}

    #- name: Build
    #  run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release

    #- name: Publish to folder
    #  run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=${{ env.WEBAPP_PACKAGE_PATH }} /p:PackageAsSingleFile=false

    #- name: Deploy to Azure WebApp
    #  uses: azure/webapps-deploy@v1
    #  with:
    #    app-name: ${{ env.WEBAPP_NAME }}
    #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #    package: ${{ env.WEBAPP_PACKAGE_PATH }}

    #- name: Publish artifacts
    #  uses: actions/upload-artifact@v1.0.0
    #  with:
    #    name: webapp
    #    path: ${{ env.WEBAPP_PACKAGE_PATH }}