name: NIRAC CI/CD

on:
  push:
    branches:
      - master

env:
  SOLUTION_NAME: NIRAC-APP.csproj
  SOLUTION_NAME_BUSINESS: NIRAC-BUSINESS/NIRAC-BUSINESS.csproj
  SOLUTION_NAME_TEST_API: API TESTE/API TESTE.csproj

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '5.0.x'

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore Dependencies BUSINESS PROJECT
      run: nuget restore ${{ env.SOLUTION_NAME_BUSINESS }} -o packages

    - name: Restore Dependencies APP
      run: nuget restore ${{ env.SOLUTION_NAME }} -o packages

    - name: Build App
      run: msbuild ${{ env.SOLUTION_NAME }} /p:Configuration=Release 

    - name: Testa toda a Aplicação
      run: test ${{ env.SOLUTION_NAME_TEST_API }} /p:Configuration=Release  /p:Build=--no-build 