name: NIRAC CI/CD

on:
  push:
    branches:
      - master

env:
  SOLUTION_NAME: NIRAC-APP.csproj
  SOLUTION_NAME_API: NIRAC-API/NIRAC-API.csproj
  SOLUTION_NAME_BUSINESS: NIRAC-BUSINESS/NIRAC-BUSINESS.csproj
  SOLUTION_NAME_TESTE: NIRAC-TESTE.csproj

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - run: cd NIRAC-TESTE

    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '5.0.x'

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore Dependencies TESTE
      run: nuget restore ${{ env.SOLUTION_NAME_TESTE }} -o packages
    
    - name: Build TESTE
      run: msbuild ${{ env.SOLUTION_NAME_TESTE }} /p:Configuration=Release 
      
    - name: Executando os testes
      run: dotnet test ${{ env.SOLUTION_NAME_TESTE }}